///get_keypress_name(Keyboard Key)
//This converts the keyboard to names (for key select with names and similar)

switch(argument0)
{
case 8: return("Backspace");exit;
case 12: return("Num 5");exit;
case 13: return("Enter");exit;
case 16: return("Shift");exit;
case 17: return("Control");exit;
case 18: return("Alt");exit;
case 19: return("Pause");exit;
case 20: return("Caps");exit;
case 27: return("Escape");exit;
case 32: return("Space");exit;
case 33: return("Page Up");exit;
case 34: return("Page Down");exit;
case 35: return("End");exit;
case 36: return("Home");exit;
case 37: return("Left Arrow");exit;
case 38: return("Up Arrow");exit;
case 39: return("Right Arrow");exit;
case 40: return("Down Arrow");exit;
case 45: return("Insert");exit;
case 46: return("Delete");exit;
case 48: return("0");exit;
case 49: return("1");exit;
case 50: return("2");exit;
case 51: return("3");exit;
case 52: return("4");exit;
case 53: return("5");exit;
case 54: return("6");exit;
case 55: return("7");exit;
case 56: return("8");exit;
case 57: return("9");exit;
case 65: return("A");exit;
case 66: return("B");exit;
case 67: return("C");exit;
case 68: return("D");exit;
case 69: return("E");exit;
case 70: return("F");exit;
case 71: return("G");exit;
case 72: return("H");exit;
case 73: return("I");exit;
case 74: return("J");exit;
case 75: return("K");exit;
case 76: return("L");exit;
case 77: return("M");exit;
case 78: return("N");exit;
case 79: return("O");exit;
case 80: return("P");exit;
case 81: return("Q");exit;
case 82: return("R");exit;
case 83: return("S");exit;
case 84: return("T");exit;
case 85: return("U");exit;
case 86: return("V");exit;
case 87: return("W");exit;
case 88: return("X");exit;
case 89: return("Y");exit;
case 90: return("Z");exit;
case 91: return("Start");exit;
case 92: return("Menu");exit;
case 96: return("Num 0");exit;
case 97: return("Num 1");exit;
case 98: return("Num 2");exit;
case 99: return("Num 3");exit;
case 100: return("Num 4");exit;
case 101: return("Num 5");exit;
case 102: return("Num 6");exit;
case 103: return("Num 7");exit;
case 104: return("Num 8");exit;
case 105: return("Num 9");exit;
case 106: return("*");exit;
case 107: return("+");exit;
case 108: return("0");exit;
case 109: return("_");exit;
case 110: return(".");exit;
case 111: return("/");exit;
case 112: return("F1");exit;
case 113: return("F2");exit;
case 114: return("F3");exit;
case 115: return("F4");exit;
case 116: return("F5");exit;
case 117: return("F6");exit;
case 118: return("F7");exit;
case 119: return("F8");exit;
case 120: return("F9");exit;
case 121: return("F10");exit;
case 122: return("F11");exit;
case 123: return("F12");exit;
case 144: return("Num Lock");exit;
case 145: return("Scroll Lock");exit;
case 186: return(";");exit;
case 187: return("=");exit;
case 188: return(",");exit;
case 189: return("-");exit;
case 190: return(".");exit;
case 191: return("/");exit;
case 192: return("`");exit;
case 222: return("'");exit;
case 265: return("a");exit;
case 266: return("b");exit;
case 267: return("c");exit;
case 268: return("d");exit;
case 269: return("e");exit;
case 270: return("f");exit;
case 271: return("g");exit;
case 272: return("h");exit;
case 273: return("i");exit;
case 274: return("j");exit;
case 275: return("k");exit;
case 276: return("l");exit;
case 277: return("m");exit;
case 278: return("n");exit;
case 279: return("o");exit;
case 280: return("p");exit;
case 281: return("q");exit;
case 282: return("r");exit;
case 283: return("s");exit;
case 284: return("t");exit;
case 285: return("u");exit;
case 286: return("v");exit;
case 287: return("w");exit;
case 288: return("x");exit;
case 289: return("y");exit;
case 290: return("z");exit;
}
return("");
